server:
  port: 8080

spring:
  application:
    name: inventory-app

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: inventory_user
    password: inventory_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # gunakan 'validate' setelah schema stabil, 'update' cukup untuk development awal
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: debug
